namespace NinjaNoMeiyo {
	namespace Models {
		enum Bitmasks {
			FLOOR_BITMASK,
			RIGHT_OBSTACLE_BITMASK,
			LEFT_OBSTACLE_BITMASK,
			CEILING_BITMASK,

			EDGE_FLOOR_RIGHT_BITMASK,
			EDGE_RIGHT_OBSTACLE_BITMASK,
			EDGE_LEFT_OBSTACLE_BITMASK,
			EDGE_FLOOR_LEFT_BITMASK,

			FLOAT_FLOOR_BITMASK,
			FLOAT_RIGHT_OBSTACLE_BITMASK,
			FLOAT_LEFT_OBSTACLE_BITMASK,
			FLOAT_CEILING_BITMASK,

			FLOAT_EDGE_FLOOR_RIGHT_BITMASK,
			FLOAT_EDGE_RIGHT_OBSTACLE_BITMASK,
			FLOAT_EDGE_LEFT_OBSTACLE_BITMASK,
			FLOAT_EDGE_FLOOR_LEFT_BITMASK,

			OIL_FLOOR_BITMASK,
			OIL_RIGHT_OBSTACLE_BITMASK,
			OIL_LEFT_OBSTACLE_BITMASK,
			OIL_CEILING_BITMASK,

			OIL_EDGE_FLOOR_RIGHT_BITMASK,
			OIL_EDGE_RIGHT_OBSTACLE_BITMASK,
			OIL_EDGE_LEFT_OBSTACLE_BITMASK,
			OIL_EDGE_FLOOR_LEFT_BITMASK,

			OIL_FLOAT_FLOOR_BITMASK,
			OIL_FLOAT_RIGHT_OBSTACLE_BITMASK,
			OIL_FLOAT_LEFT_OBSTACLE_BITMASK,
			OIL_FLOAT_CEILING_BITMASK,

			OIL_FLOAT_EDGE_FLOOR_RIGHT_BITMASK,
			OIL_FLOAT_EDGE_RIGHT_OBSTACLE_BITMASK,
			OIL_FLOAT_EDGE_LEFT_OBSTACLE_BITMASK,
			OIL_FLOAT_EDGE_FLOOR_LEFT_BITMASK,

			AIR_BITMASK,
			RYUNOSUKE_BITMASK,

			FIXED_OBSTACLE_BITMASK
		};
	}
}